### ISSUE TITLE
LightblueUtil.isFieldAnArrayCount() is not correct

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-ldap#16]
The correct way to check if "name#" is an array size is to check whether "name" is an array. Current implementation only checks if name ends with "#".

**Comment by dcrissman** [comment]
Can I assume that only field names followed by a '#' are candidates to be array counts? So if I see a field name postfixed with a '#', then I should check for an array?

**Comment by bserdar** [comment]
Yes.

**Comment by dcrissman** [comment]
@bserdar merged #16, but with the understanding that more work is to be done. I will submit additional changes as a new PR.

Remaining work:
>@bserdar
> Fields.get() will return a field only if it is the immediate child of that Fields instance.
> Are you sure the fieldName is not an array inside an object?
> For field names, use Path in general.

**Comment by bserdar** [comment]
Continuing:

Once you change fieldName to Path, you'll need to use schema.resolve(), or
entityMetadata.resolve().

That throws exception if it can't find a field, so catch it and ignore it.

**Comment by dcrissman** [comment]
This may be addressed in #17

**Comment by dcrissman** [comment]
https://github.com/lightblue-platform/lightblue-ldap/pull/29 has been submitted as a fix to #17. If that does not address your concerns, then lets talk about creating a test case that reproduces this scenario.

**Comment by dcrissman** [comment]
I believe any remaining work on this issue was either addressed in #17 or will be addressed in #30. If there is nothing further for this issue, can it be closed out?

**Comment by bserdar** [comment]
yes.

**Comment by dcrissman** [comment]
Closing issue
