### ISSUE TITLE
Type system is not used

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-ldap#17]
LDAP record is constructed from node.asText() values, no metadata information is used. Iterate metadata nodes, get node types, and type-cast the node values using the type system to string.

**Comment by dcrissman** [comment]
The Type system is used in other places such as ResultTranslator. 

I see asText() being used in both LdapDataSourceConfiguration and LdapCRUDController, is your issue in reference to one or the other or both? In any case, I am unclear how you want this changed?

I could use StringType.TYPE.fromJson() directly if you prefer, but it returns an Object which then needs the toString() called on it. Maybe we could change Type to be a generic that could just return the specific type?

**Comment by bserdar** [comment]
StringType.Type.fromJson assumes that you have string data in json.

To get the value from a JSON doc, use:

Object value=fieldType.fromJson();

Then, you can translate 'value' to a LDAP compliant string.

**Comment by bserdar** [comment]
This translation logic should be applied for queries as well as documents.
Take Date fields for example. The Lightblue Date queries will come as
strings formatted the way Lightblue understands. You have to translate
those to LDAP dates when you translate the query.

**Comment by dcrissman** [comment]
PR https://github.com/lightblue-platform/lightblue-ldap/pull/29
