### ISSUE TITLE
Is translation of ArrayContainsExpression correct

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-ldap#20]
The translation creates a filter of the form:

AND: { field=value1, field=value2, field=value3...}

Is this really correct? How does LDAP do this? How are array fields represented in LDAP?

**Comment by dcrissman** [comment]
I am no LDAP expert, but I believe this to be correct. An array filter looking for multiple values should be of form eg. (&(somekey=somevalue)(somekey=someothervalue))

Look at the first example on this page, objectClass is usually (always?) an array in ldap:
https://confluence.atlassian.com/display/DEV/How+to+Write+LDAP+Search+Filters

**Comment by bserdar** [comment]
So a field can appear more than once, and each value can be represented as
an array element. Your filter should work, in that case.

**Comment by dcrissman** [comment]
That is correct.

I am going to go ahead and close this issue out, but feel free to re-open if you have further questions.
