### ISSUE TITLE
ResultTranslator.toJson should use Types correctly

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-ldap#21]
Instead of 

if(type instanceof ...) {
   ...
}

use type.toJson(value)

**Comment by dcrissman** [comment]
I am using type.toJson on line 149. I need the instanceof checks in order to pull the data off the LDAP attribute properly.

**Comment by bserdar** [comment]
In that case, for most cases:

  type.toJson(attr.getValue())

should suffice, because most types can cast a string to the appropriate
value.

For Date, you have to test. What is the date format used by LDAP? Is that
compatible with what we are using? If so, toJson should be able to handle
that as well. otherwise, you have to translate. DateType.DATE_FORMAT_STR is
our date format.

For binary, you have to have a special case.

**Comment by dcrissman** [comment]
Looks like dates take this format:
Attribute(name=modifyTimestamp, values={'20150114171835.347Z'})

**Comment by bserdar** [comment]
That'll need translation. Convert it to Date in your translator..

**Comment by dcrissman** [comment]
I am passing the Date from LDAP into the DateType.toJson method, which does the formatting.

**Comment by dcrissman** [comment]
This is ready for review.
