### ISSUE TITLE
Define objectClass in metadata

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-ldap#24]
The objectClass(es) used for an entity should theoretically be the same for all instances of that entity. If that is the case (confirm?), then there is no need to include in each insert statement.

**Comment by bserdar** [comment]
What do you mean by "include in each insert statement"?

**Comment by dcrissman** [comment]
An LDAP entity has the concept of an objectClass, which is similar to a java interface. It indicates what fields an entity has and which ones are required or optional. An entity can have multiple objectClasses (not sure if it could have none). Technically, each instance of an entity can have different objectClasses assigned to it.

eg. You could have a User entity that has a special objectClass to define what type of User it is, or maybe certain users have special needs and therefore extra objectClasses.

Currently in Lightblue objectClasses are assigned during the insert. What I am wondering is if for lightblue purposes, the objectClasses could be consistent from one instance of an entity to another? This is likely a question for an LDAP administrator?

**Comment by bserdar** [comment]
objectType determines the entity type in Lightblue. It can't be different
from one instance of an entity to another.

**Comment by dcrissman** [comment]
Just to make sure there wasn't any confusion, I was speaking about objectClass not objectType. That clarified, if I understand you correctly, then it sounds like each unique set of objectClass(es) would need to be it's own lightblue entity, even if it acts on similar LDAP entries.

For example, say you have two User entries in LDAP, but they have different subsets of objectClass(es), then these two users would need to have two separate entities?

**Comment by bserdar** [comment]
Each unique set of objectClasses wouldn't need to be it's own entity. The
lightblue entity can be the union of all those objectClasses, then you can
represent different types of LDAP users using the same lightblue entity.

**Comment by dcrissman** [comment]
That being the case, then if we did implement this feature we would want it to be optional. To that I say, lets hold off on this and see if we get an RFE. I will close this issue for now.

For posterity (and as an experiment to see if it sticks around after I delete the branch in my own repo), I pushed the incomplete changes I had started up.
