### ISSUE TITLE
entityInfo/datastore/uniqueattr should always be required in schema/fields 

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-ldap#25]
Find a way to enforce this.

**Comment by jewzaam** [comment]
Parser could do that enforcement?

----- Original Message -----

**Comment by bserdar** [comment]
You can make sure the field exists in metadata hooks.

**Comment by dcrissman** [comment]
@bserdar Do you mean the getMetadataListener method on CRUDController implementations?

**Comment by bserdar** [comment]
Yes. Methods of MetadataListener will be called during metadata operations,
and you can make check if any backend required fields are present, and
insert them if not.

**Comment by dcrissman** [comment]
Ready for review
