### ISSUE TITLE
Support ObjectField for LDAP.

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-ldap#30]
Support Lightblue's ObjectField and ObjectArray concepts for LDAP. 

LDAP stores it's data on an entry as flat key/value pairs. We will need to figure out what an object would mean in the LDAP world before implementation can begin.

**Comment by dcrissman** [comment]
From a discussion with @bserdar, we are thinking that an object defined in the entity metadata could just be a subset of attributes grouped together in a different logical but meaningful way. So maybe for example:

define objectClass Person {fname, lname}
define objectClass Address {city, zipcode}

Entry has both Person & Address objectClasses. You may want to represent the Address in Lightblue as an object on the Person entity. LDAP would still store the data flat, but you would have a different logical view via Lightblue.

**Comment by bserdar** [comment]
Options:
- Come up with a naming scheme LDAP supports to represent hierarchies. If '.' is supported in attribute names, simple using the full field name solves the problem
 - Let the metadata specify field->attribute name mappings using properties

**Comment by dcrissman** [comment]
@bserdar created #31 to handle the field->attribute mapping.

**Comment by dcrissman** [comment]
As best I can tell, Ldap has no issue with a '.' in the attribute name, however, it considers it a different attribute and requires it defined on an objectClass.

For example, say the following objectClass existed:
define objectClass Person {name}

If you created an Entry with Attribute{name = 'Dennis'}, it would work fine. However, Attribute{name.first = 'Dennis'} would fail because 'name.first' is not a valid attribute based on the assigned objectClass(es).

The following would solve the problem, but then it would just be another flat attribute on the Entry. Aside from that, an sub-object defined this way doesn't really mesh with the way ldap is used, and so I suspect is simply wouldn't be.
define objectClass Person {name, name.first}

**Comment by bserdar** [comment]
Representation of a json document with nested object doesn't have to
reflect the same hierarchical structure in ldap. It is perfectly fine if
you flatten the json document to store in ldap, and unflatten when you're
converting it back to json. If you use JsonDoc.modify, you don't even have
to worry about the intermediate objects, because that call will create them
in json.

**Comment by dcrissman** [comment]
> Come up with a naming scheme LDAP supports to represent hierarchies. If '.' is supported in attribute names, simple using the full field name solves the problem

@bserdar I am fine with the idea of Lightblue logically representing the otherwise flat data as an entity with sub-objects as defined in the metadata. Your quoted statement above I think is what confused me. If I did not answer your question, would you please clarify what you meant?

**Comment by bserdar** [comment]
Sorry for the confusion. The "naming scheme" I mentioned in that statement
is "flattened" representation of a json doc, that is, use "." in field
names.

**Comment by dcrissman** [comment]
@bserdar and I decided that we are not going to support object arrays for LDAP at this time. The main reason for this decision is that LDAP doesn't play nice with attributes named "x.y[1].z". That would require an objectClass with each array value defined, which doesn't really make sense. If we can find a good use case and a way to make it work, then we can revisit at a later date.

For now, I am updating the subject of this issue to reflect.

**Comment by dcrissman** [comment]
For this field definition (Sample 1), say you wanted to alias 'st' to being 'state'. Go ahead and change 'st' to 'state' and then in 'fieldsToAttributes' (Sample 2) use the full field path but then just the flat ldap attribute name.

Sample 1:
```json
    "fields": {
                "uid": {"type": "string"},
                "givenName": {"type": "string"},
                "sn": {"type": "string"},
                "cn": {"type": "string"},
                "address": {
                    "type": "object",
                    "fields": {
                        "street": {"type": "string"},
                        "postalCode": {"type": "integer"},
                        "st": {"type": "string"}
                    }
                }
            }
```
Sample 2:
```json
"fieldsToAttributes": [
                {
                    "field": "address.state",
                    "attribute": "st"
                }
            ]
```

**Comment by dcrissman** [comment]
Ready for review
