### ISSUE TITLE
Remove lightblue version properties in pom

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-ldap#33]
Just hard code them, the release and version plugins manage these well.  I think the release plugin will remove the property anyway, so it's a wasted effort.  Just define the in the root pom's `dependencyManagement` one time.

**Comment by dcrissman** [comment]
Does these utilities try and upgrade/downgrade dependencies? How do we maintain that we are using latest or consistent stuff?

**Comment by jewzaam** [comment]
It's managed by the release scripts in each repo.  They may need some updates.  A quick look shows it's using the `versions:update-properties` goal and it probably should be changed to the `versions:use-releases` goal.  FYI @derek63 (re: upcoming Ana release)
