### ISSUE TITLE
Use Path instead of String field Names

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-ldap#42]

**Comment by bserdar** [comment]
LdapFieldNameTranslator, EntryBuilder should use Path for field names.

**Comment by dcrissman** [comment]
Ready for review

**Comment by dcrissman** [comment]
@bserdar now that #30 has been closed out, can this issue also be closed?

**Comment by bserdar** [comment]
yes

**Comment by dcrissman** [comment]
closing
