### ISSUE TITLE
In datasources.json use datasource instead of database

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-ldap#66]
A database is a physical thing. a datasource is a logical thing

**Comment by bserdar** [comment]
Is this correct? Is it being used in datasources.json? 

When you're referring to an entity in datasources.json, use "datasource".

When you're referring to a physical database in a datasource definition (i.e. in datasources.json), use "database".

**Comment by dcrissman** [comment]
I am using database in the datasources.json, see:
https://github.com/lightblue-platform/lightblue-ldap/blob/master/lightblue-ldap-integration-test/src/test/resources/datasources.json#L4

I don't believe ldap supports the notion of a datasource at this time. So should it support both? Or only datasource? If it does support both, then should one take precedence, or how does that work?

**Comment by bserdar** [comment]
I think the use of "database" in "myldapserver" is correct.

When you're referring to "myldapserver", use "datasource".

**Comment by dcrissman** [comment]
@bserdar Thanks, then this is a noop.
