### ISSUE TITLE
Builds fail after changes in snapshot stuff somewhere

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-ldap#81]
https://travis-ci.org/lightblue-platform/lightblue-ldap

Only an issue because we bundle this into lightblue-rest right now.  Bundling issue goes away with https://github.com/lightblue-platform/lightblue-rest/pull/193

**Comment by dcrissman** [comment]
I suspect this was resolved in https://github.com/lightblue-platform/lightblue-ldap/pull/82
